sudo apm install monokai
sudo apm install monokai-dark
sudo apm install monokai-seti
sudo apm install minimap
sudo apm install minimap-color-highlight
sudo apm install minimap-git-diff
sudo apm install minimap-find-and-replace
sudo apm install language-ejs
sudo apm install langugae-ini
sudo apm install language-sass
sudo apm install language-less
sudo apm install language-moustache
sudo apm install tabs-to-spaces
sudo apm install emmet
sudo apm install editorconfig
sudo apm install Spectacular
sudo apm install atom-beautify
sudo apm install autocomplete-plus
sudo apm install caniuse
sudo apm install git-plus
sudo apm install linter
sudo apm install mocha
sudo apm install seti-ui
