apm install atom-beautify
apm install atom-html-preview
apm install atom-material-syntax
apm install atom-material-ui
apm install atom-ternjs
apm install autocomplete-html-entities
apm install autocomplete-modules
apm install autocomplete-php
apm install caniuse
apm install clipboard-plus
apm install editorconfig
apm install emmet
apm install file-icons
apm install git-plus
apm install javascript-snippets
apm install language-apache
apm install language-babel
apm install language-ejs
apm install language-ini
apm install language-javascript-jsx
apm install linter
apm install linter-jshint
apm install linter-sass-lint
apm install linter-scss-lint
apm install material
apm install material-ui
apm install merge-conflicts
apm install minimap
apm install minimap-find-and-replace
apm install minimap-git-diff
apm install minimap-highlight-selected
apm install mocha
apm install monokai
apm install monokai-dark
apm install multiple-cursors-clipboard
apm install quick-editor
apm install split-diff
apm install tabs-to-spaces
apm install to-base64
apm install url-encode
apm install webbox-color
